# AUTO-GENERATED by render_dag.py — do not hand-edit.
# Edit pipelines/finance_etl_daily.yml and re-run render_dag.py instead.
# ============================================
# Airflow DAG: finance_etl_daily
# Purpose: Daily GL transactions ETL: extract via API → load Postgres → dbt run → dbt test
# ============================================

"""Daily GL transactions ETL: extract via API → load Postgres → dbt run → dbt test"""

from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.exceptions import AirflowSkipException
from datetime import datetime, timedelta


def extract_load(**context):
    """Fetch GL transactions from FastAPI and load into Postgres via PostgresHook.

    Uses Airflow's ``postgres_default`` connection (configured via
    ``AIRFLOW_CONN_POSTGRES_DEFAULT`` in docker-compose) so that no
    credentials are stored in code.  Raises AirflowSkipException when the
    API returns zero rows, preventing downstream dbt runs on empty data.
    """
    from api.extract_load import fetch_raw_data, load_data_to_db

    raw_data = fetch_raw_data()
    row_count = len(raw_data)

    if row_count == 0:
        raise AirflowSkipException("No rows returned from API — skipping dbt run/test.")

    hook = PostgresHook(conn_id="postgres_default")
    conn = hook.get_conn()  # psycopg2 connection — lifecycle owned by hook

    try:
        load_data_to_db(raw_data, conn=conn)
    finally:
        conn.close()

    print(f"Extract/load complete — {row_count} rows processed.")


# Default arguments for the DAG
default_args = {
    "owner": "data-eng",
    "retries": 3,
    "retry_delay": timedelta(minutes=2),
    "retry_exponential_backoff": True,
    "max_retry_delay": timedelta(minutes=30),
    "execution_timeout": timedelta(minutes=30),
}

with DAG(
    dag_id="finance_etl_daily",
    description="Daily GL transactions ETL: extract via API → load Postgres → dbt run → dbt test",
    schedule="@daily",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["finance", "etl", "dbt", "gl"],
    max_active_runs=1,
    doc_md=__doc__,
) as dag:

    extract_load_task = PythonOperator(
        task_id="extract_load",
        python_callable=extract_load,
        sla=timedelta(minutes=30),
        doc_md="Fetch GL transactions from FastAPI, upsert into finance.gl_transactions via PostgresHook.",
    )

    dbt_run_all = BashOperator(
        task_id="dbt_run_all",
        bash_command="dbt run",
        cwd="/opt/airflow/dbt",
        sla=timedelta(hours=1),
        doc_md="Run all dbt models (staging → refined → marts).",
    )

    dbt_test_all = BashOperator(
        task_id="dbt_test_all",
        bash_command="dbt test",
        cwd="/opt/airflow/dbt",
        sla=timedelta(minutes=30),
        doc_md="Run all dbt tests to validate data quality.",
    )

    trial_balance_run = BashOperator(
        task_id="trial_balance_run",
        bash_command="dbt run --models trial_balance_by_month",
        cwd="/opt/airflow/dbt",
        sla=timedelta(minutes=15),
        doc_md="Rebuild the trial_balance_by_month mart (generated artifact).",
    )

    income_statement_run = BashOperator(
        task_id="income_statement_run",
        bash_command="dbt run --models income_statement_by_month",
        cwd="/opt/airflow/dbt",
        sla=timedelta(minutes=15),
        doc_md="Rebuild the income_statement_by_month mart (generated artifact).",
    )

    balance_sheet_run = BashOperator(
        task_id="balance_sheet_run",
        bash_command="dbt run --models balance_sheet_by_month",
        cwd="/opt/airflow/dbt",
        sla=timedelta(minutes=15),
        doc_md="Rebuild the balance_sheet_by_month mart (generated artifact).",
    )

    gross_profit_mom_variance_run = BashOperator(
        task_id="gross_profit_mom_variance_run",
        bash_command="dbt run --models gross_profit_mom_variance",
        cwd="/opt/airflow/dbt",
        sla=timedelta(minutes=15),
        doc_md="Rebuild the gross_profit_mom_variance mart (generated artifact).",
    )

    account_aging_run = BashOperator(
        task_id="account_aging_run",
        bash_command="dbt run --models account_aging",
        cwd="/opt/airflow/dbt",
        sla=timedelta(minutes=15),
        doc_md="Rebuild the account_aging mart (generated artifact).",
    )


    # Dependency chain — stages run in listed order; marts chain sequentially.
    extract_load_task >> dbt_run_all >> dbt_test_all >> trial_balance_run >> income_statement_run >> balance_sheet_run >> gross_profit_mom_variance_run >> account_aging_run
